const {chromium}=require('playwright');const http=require('http'),fs=require('fs'),path=require('path');
(async()=>{const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{let p=path.join(root,req.url.split('?')[0]);if(p.endsWith('/'))p+='index.html';try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':p.endsWith('.json')?'application/json':p.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end('not found');}}).listen(8769);
const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await b.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('console',m.text())});await page.goto('http://localhost:8769/enhance/');
// Deterministic low-contrast photograph-like test target, not a marketing example.
const fixture=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=320;c.height=240;const x=c.getContext('2d');let g=x.createLinearGradient(0,0,0,240);g.addColorStop(0,'#7b9bb0');g.addColorStop(.55,'#b4b8b0');g.addColorStop(1,'#727b67');x.fillStyle=g;x.fillRect(0,0,320,240);x.fillStyle='#4c6962';x.beginPath();x.moveTo(0,160);x.lineTo(75,62);x.lineTo(178,173);x.lineTo(243,98);x.lineTo(320,165);x.lineTo(320,240);x.lineTo(0,240);x.fill();x.fillStyle='#d3bf96';x.fillRect(110,148,88,65);x.fillStyle='#736657';x.beginPath();x.moveTo(100,150);x.lineTo(154,108);x.lineTo(208,150);x.fill();x.fillStyle='#4b5658';x.fillRect(146,175,18,38);x.fillRect(122,164,14,15);x.fillRect(176,164,14,15);const a=x.getImageData(0,0,320,240);let seed=19;for(let i=0;i<a.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;const n=((seed>>>24)/255-.5)*14;for(let j=0;j<3;j++)a.data[i+j]+=n;}x.putImageData(a,0,0);return c.toDataURL('image/png').split(',')[1];});fs.writeFileSync('/tmp/enhance-test.png',Buffer.from(fixture,'base64'));
await page.setInputFiles('#fileInput','/tmp/enhance-test.png');await page.waitForSelector('#workspace:not([hidden])');await page.selectOption('#scale','2');await page.click('#apply');await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('finished'),{},{timeout:60000});console.log('FAST',await page.locator('#resultInfo').textContent());await page.screenshot({path:'/tmp/lumen-enhance-desktop.png'});

await page.selectOption('#engine','ai');await page.click('#apply');await page.waitForTimeout(500);await page.click('#cancel');console.log('cancel',await page.locator('#status').textContent(),await page.locator('#download').isDisabled());
// Worker numerical regressions: identity, colour noise reduction, alpha preservation.
const metrics=await page.evaluate(async()=>{const run=(data,w,h,settings)=>new Promise((res,rej)=>{const worker=new Worker('/enhance/finish-worker.js');worker.onmessage=({data:d})=>{if(d.done){worker.terminate();res(new Uint8ClampedArray(d.buffer));}if(d.error)rej(d.error);};worker.postMessage({buffer:data.buffer,width:w,height:h,settings},[data.buffer]);});let a=new Uint8ClampedArray(32*32*4);for(let i=0;i<1024;i++){const n=(i%7-3)*3;a[i*4]=120+n;a[i*4+1]=120-n;a[i*4+2]=120+n;a[i*4+3]=i%5?255:0;}const original=a.slice();const off=await run(a,32,32,{detail:0,noise:0,light:0,colour:0});const reduced=await run(original.slice(),32,32,{detail:0,noise:100,light:0,colour:0});let v1=0,v2=0,alpha=true;for(let i=0;i<1024;i++){if(original[i*4+3]){v1+=Math.pow(original[i*4]-120,2);v2+=Math.pow(reduced[i*4]-120,2);}if(original[i*4+3]!==reduced[i*4+3])alpha=false;}return {identity:off.every((v,i)=>v===original[i]),denoiseVarianceRatio:v2/v1,alpha};});console.log('WORKER',metrics);if(!metrics.identity||!metrics.alpha||metrics.denoiseVarianceRatio>=.5)throw Error('Worker quality regression');
await page.evaluate(()=>{const c=document.createElement('canvas');c.width=20;c.height=20;const x=c.getContext('2d');x.fillStyle='#f00';x.fillRect(5,5,10,10);window.testPNG=c.toDataURL().split(',')[1];});const transparent=await page.evaluate(()=>window.testPNG);fs.writeFileSync('/tmp/enhance-alpha.png',Buffer.from(transparent,'base64'));await page.setInputFiles('#fileInput','/tmp/enhance-alpha.png');await page.waitForTimeout(300);await page.selectOption('#engine','ai');await page.click('#apply');await page.waitForFunction(()=>document.getElementById('message').textContent.includes('transparency'));console.log('alpha AI rejection',await page.locator('#message').textContent());await page.selectOption('#engine','fast');await page.click('#apply');await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('finished'));const pngPromise=page.waitForEvent('download');await page.click('#download');await (await pngPromise).saveAs('/tmp/enhance-alpha-output.png');await page.selectOption('#format','image/jpeg');const dl=page.waitForEvent('download');await page.click('#download');const d=await dl;await d.saveAs('/tmp/enhance-export.jpg');console.log('export',d.suggestedFilename());await page.locator('#detail').fill('55');console.log('invalidates',await page.locator('#download').isDisabled());await page.click('#clear');console.log('clear',await page.locator('#workspace').isHidden());if(errors.length)throw Error(errors.join('; '));console.log('errors',errors);await b.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
