(() => {
const $=id=>document.getElementById(id);let items=[],next=0,busy=false,generation=0;
const status=(i,t,cls='')=>{i.status.textContent=t;i.status.className='item-status '+cls;};
const message=(t)=>$('message').textContent=t;
function invalidate(i){i.version++;i.blob=null;i.save.disabled=true;if(i.url)URL.revokeObjectURL(i.url);i.url=null;}
function refresh(){for(const n of ['format','shape'])$(n).disabled=busy;$('downloadAll').disabled=busy||!items.some(i=>i.blob);$('quality').disabled=busy||$('format').value==='png';$('qualityValue').textContent=$('format').value==='png'?'lossless':$('quality').value+'%';}
async function transform(i){const c=document.createElement('canvas'),swap=i.turn%2;c.width=swap?i.original.height:i.original.width;c.height=swap?i.original.width:i.original.height;const x=c.getContext('2d');x.translate(c.width/2,c.height/2);x.rotate(i.turn*Math.PI/2);x.scale(i.flipX?-1:1,i.flipY?-1:1);x.drawImage(i.original,-i.original.width/2,-i.original.height/2);const bitmap=await createImageBitmap(c);if(i.removed){bitmap.close();return;}i.bitmap?.close();i.bitmap=bitmap;i.crop=null;await render(i);}
async function render(i){if(!i.bitmap||i.removed)return;invalidate(i);const version=i.version,ticket=generation;status(i,'preparing export');i.preview.setAttribute('aria-busy','true');try{let r=i.crop||{x:0,y:0,w:i.bitmap.width,h:i.bitmap.height};if($('shape').value==='circle'){const size=Math.min(r.w,r.h);r={x:r.x+(r.w-size)/2,y:r.y+(r.h-size)/2,w:size,h:size};}const c=document.createElement('canvas');c.width=Math.max(1,Math.round(r.w));c.height=Math.max(1,Math.round(r.h));const x=c.getContext('2d'),format=$('format').value;if(format==='jpeg'){x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);}x.save();x.beginPath();if($('shape').value==='circle')x.arc(c.width/2,c.height/2,c.width/2,0,2*Math.PI);else if($('shape').value==='rounded')x.roundRect(0,0,c.width,c.height,Math.min(c.width,c.height)*.08);else x.rect(0,0,c.width,c.height);x.clip();x.drawImage(i.bitmap,r.x,r.y,r.w,r.h,0,0,c.width,c.height);x.restore();const blob=await new Promise(resolve=>c.toBlob(resolve,'image/'+format,+$('quality').value/100));if(version!==i.version||ticket!==generation||i.removed)return;if(!blob)throw Error('Could not encode this image.');if(items.reduce((s,a)=>s+(a.blob?.size||0),0)+blob.size>400*1024*1024)throw Error('400 MB result cap. Save and start a smaller batch.');i.blob=blob;i.ext=blob.type==='image/jpeg'?'jpg':blob.type==='image/webp'?'webp':'png';i.url=URL.createObjectURL(blob);i.image.src=i.url;i.save.disabled=false;i.meta.textContent=`${i.bitmap.width} × ${i.bitmap.height} source → ${c.width} × ${c.height} crop · ${L.fmtBytes(blob.size)}`;status(i,'ready / '+$('shape').selectedOptions[0].textContent,'ready');}catch(e){if(version===i.version)status(i,e.message,'err');}finally{if(version===i.version)i.preview.setAttribute('aria-busy','false');refresh();}}
async function add(files){if(busy){message('finish this operation before adding more.');return;}busy=true;refresh();const ticket=generation;for(const f of files){if(ticket!==generation)break;if(items.length>=50){message('50 images per batch.');break;}if(f.size>40*1024*1024||!f.size||!['image/jpeg','image/png','image/webp'].includes(f.type)){message('skipped unsupported or oversized file: '+f.name);continue;}if(items.reduce((n,i)=>n+i.file.size,0)+f.size>300*1024*1024){message('300 MB input limit. Save and clear this batch.');break;}const row=document.createElement('article');row.className='crop-item';row.innerHTML='<div class="item-head"><div class="item-name"></div><button class="save" disabled>save</button></div><div class="item-preview"><img alt="Cropped output preview"></div><div class="item-tools"><button class="primary edit" disabled>crop image</button><button class="left" disabled>rotate left</button><button class="right" disabled>rotate right</button><button class="flipx" disabled>flip ↔</button><button class="flipy" disabled>flip ↕</button><button class="copy" disabled>crop to batch</button><button class="reset" disabled>reset</button></div><div class="item-meta"></div><div class="item-status"></div>';$('list').append(row);const i={id:++next,file:f,row,version:0,turn:0,flipX:false,flipY:false,crop:null,original:null,bitmap:null,blob:null,url:null,removed:false,save:row.querySelector('.save'),image:row.querySelector('img'),preview:row.querySelector('.item-preview'),meta:row.querySelector('.item-meta'),status:row.querySelector('.item-status')};row.querySelector('.item-name').textContent=f.name;items.push(i);status(i,'reading image');try{i.original=await createImageBitmap(f);if(ticket!==generation||i.removed){i.original.close();break;}if(i.original.width*i.original.height>24000000)throw Error('Over 24 MP. Resize first.');if(items.reduce((n,a)=>n+(a.original?a.original.width*a.original.height:0),0)>60000000)throw Error('60 MP decoded batch limit. Save and clear before adding more.');await transform(i);row.querySelectorAll('.item-tools button').forEach(b=>b.disabled=false);}catch(e){status(i,'could not load image / '+e.message,'err');i.original?.close();i.original=null;continue;}
i.save.onclick=()=>i.blob&&L.download(i.blob,f.name.replace(/\.[^.]+$/,'')+'-crop.'+i.ext);row.querySelector('.edit').onclick=()=>{if(busy)return;CropEditor.open(i.bitmap,i.crop,f.name,r=>{i.crop=r;render(i);});};
async function change(fn){if(busy)return;busy=true;refresh();row.querySelectorAll('.item-tools button').forEach(b=>b.disabled=true);fn();try{await transform(i);}catch(e){status(i,e.message,'err');}finally{row.querySelectorAll('.item-tools button').forEach(b=>b.disabled=false);busy=false;refresh();}}
row.querySelector('.left').onclick=()=>change(()=>i.turn=(i.turn+3)%4);row.querySelector('.right').onclick=()=>change(()=>i.turn=(i.turn+1)%4);row.querySelector('.flipx').onclick=()=>change(()=>i.flipX=!i.flipX);row.querySelector('.flipy').onclick=()=>change(()=>i.flipY=!i.flipY);row.querySelector('.reset').onclick=()=>change(()=>{i.turn=0;i.flipX=i.flipY=false;});row.querySelector('.copy').onclick=async()=>{if(busy)return;if(!i.crop){message('crop this image first, then copy its crop.');return;}busy=true;const ticket=generation,r=i.crop,fractions={x:r.x/i.bitmap.width,y:r.y/i.bitmap.height,w:r.w/i.bitmap.width,h:r.h/i.bitmap.height};message('applying the same proportional crop / originals kept');for(const a of items){if(ticket!==generation)break;if(!a.bitmap||a.removed)continue;const x=Math.round(fractions.x*a.bitmap.width),y=Math.round(fractions.y*a.bitmap.height);a.crop={x,y,w:Math.max(1,Math.min(a.bitmap.width-x,Math.round(fractions.w*a.bitmap.width))),h:Math.max(1,Math.min(a.bitmap.height-y,Math.round(fractions.h*a.bitmap.height)))};await render(a);}busy=false;message('batch crop applied. check each preview before saving.');refresh();};
}busy=false;refresh();}
async function rerender(){if(busy){message('finish the current operation before changing output settings.');return;}busy=true;refresh();const ticket=generation;for(const i of items){if(ticket!==generation)break;await render(i);}busy=false;refresh();}
L.dropzone($('dropzone'),$('fileInput'),add);['format','shape'].forEach(n=>$(n).addEventListener('change',rerender));$('quality').addEventListener('input',()=>{refresh();items.forEach(invalidate);});$('quality').addEventListener('change',rerender);
$('downloadAll').onclick=async()=>{if(busy)return;busy=true;refresh();try{const zip=new JSZip();items.filter(i=>i.blob).forEach(i=>zip.file(i.id+'-'+i.file.name.replace(/\.[^.]+$/,'')+'-crop.'+i.ext,i.blob));L.download(await zip.generateAsync({type:'blob'}),'lumen-crops.zip');}finally{busy=false;refresh();}};
$('clearAll').onclick=()=>{generation++;CropEditor.close();items.forEach(i=>{i.removed=true;invalidate(i);i.bitmap?.close();i.original?.close();});items=[];$('list').textContent='';message('');busy=false;refresh();};refresh();
})();
