(() => {
const $=id=>document.getElementById(id),rates={opus:[32,48,64,96,128,160,192,256],mp3:[64,96,128,160,192,224,256,320]};let items=[],next=1,busy=false,generation=0,worker=null,rejectWorker=null;const dur=s=>Math.floor(s/60)+':'+String(Math.round(s%60)).padStart(2,'0');
const settings=()=>({codec:$('codec').value,bitrate:rates[$('codec').value][+$('quality').value],mono:$('channels').value==='mono',rate:$('codec').value==='opus'?48000:$('rate').value==='auto'?44100:+$('rate').value});
const key=()=>JSON.stringify(settings());function msg(t,error=false){$('message').textContent=t;$('message').className='msg'+(error?' err':'');}
function setStatus(i,t,error=false){i.status.textContent=t;i.status.className='status'+(error?' err':'');}
function dispose(i){if(i.url)URL.revokeObjectURL(i.url);i.url=null;i.blob=null;i.outputKey=null;i.save.disabled=true;i.ab.disabled=true;i.player.pause();i.player.src=i.original;i.a.classList.add('selected');i.ab.classList.remove('selected');}
function update(){const s=settings();$('bitrate').textContent=s.bitrate+' kbps';$('rate').disabled=busy||s.codec==='opus';$('qualityNote').textContent=s.codec==='opus'?'Opus VBR / complexity 10. estimates are approximate; final size depends on the audio.':'MP3 constant bitrate. higher bitrate keeps more detail but uses more space.';let ready=0,total=0;for(const i of items){if(i.blob&&i.outputKey===key()){ready++;total+=i.blob.size;}else if(i.duration)i.sizes.textContent='estimate '+L.fmtBytes(i.duration*s.bitrate*125*(s.codec==='opus'?1.06:1.01))+' / '+L.fmtBytes(i.file.size)+' original';} $('summary').textContent=items.length?`${items.length} files · ${ready} ready`+(ready?' · '+L.fmtBytes(total):''):'';$('compress').disabled=busy||!items.length;$('zip').disabled=busy||!ready;}
function changed(){items.forEach(dispose);items.forEach(i=>setStatus(i,'settings changed / compress to apply'));update();}
function busyState(on){busy=on;for(const n of ['codec','channels','quality','rate'])$(n).disabled=on;$('cancel').hidden=!on;$('clear').disabled=on;update();}
function cancel(){generation++;worker?.terminate();worker=null;rejectWorker?.(Error('Cancelled'));rejectWorker=null;items.forEach(i=>{i.progress.hidden=true;if(i.status.textContent.includes('encoding')||i.status.textContent.includes('decoding'))setStatus(i,'cancelled / original kept');});busyState(false);}
async function decode(file,sampleRate){const context=new OfflineAudioContext(2,1,sampleRate);return context.decodeAudioData(await file.arrayBuffer());}
function metadata(i,b){i.duration=b.duration;i.sampleRate=b.sampleRate;i.channels=b.numberOfChannels;i.meta.textContent=`${dur(b.duration)} · ${b.numberOfChannels===1?'mono':b.numberOfChannels===2?'stereo':b.numberOfChannels+' channels'} · ${Math.round(b.sampleRate/100)/10} kHz decode · ${L.fmtBytes(i.file.size)}`;}
async function add(files){if(busy){msg('finish or cancel the current batch before adding files.');return;}let added=0;for(const f of files){if(items.length>=20){msg('20 files per batch. compress these, then start another batch.');break;}if(!f.size||f.size>80*1024*1024){msg('skipped '+f.name+': needs a non-empty file under 80 MB.',true);continue;}if(items.some(i=>i.file.name===f.name&&i.file.size===f.size&&i.file.lastModified===f.lastModified))continue;
const i={id:next++,file:f,blob:null,url:null,duration:0};i.original=URL.createObjectURL(f);const row=document.createElement('article');row.className='audio-card';row.innerHTML='<div class="cardhead"><div><div class="filename"></div><div class="meta"></div></div><button class="save" disabled>save</button></div><div class="sizes"></div><div class="status"></div><progress max="100" value="0" hidden></progress><div class="preview"><button class="original selected">original</button><button class="compressed" disabled>compressed</button><span>switch at the same playback position</span></div><audio class="player" controls preload="metadata"></audio>';$('list').append(row);Object.assign(i,{row,meta:row.querySelector('.meta'),sizes:row.querySelector('.sizes'),status:row.querySelector('.status'),save:row.querySelector('.save'),progress:row.querySelector('progress'),player:row.querySelector('audio'),a:row.querySelector('.original'),ab:row.querySelector('.compressed')});row.querySelector('.filename').textContent=f.name;i.meta.textContent=L.fmtBytes(f.size);i.player.src=i.original;
i.player.addEventListener('loadedmetadata',()=>{if(Number.isFinite(i.player.duration)&&!i.duration){i.duration=i.player.duration;update();}});
const switchTo=(output)=>{const url=output?i.url:i.original;if(!url)return;const t=i.player.currentTime,playing=!i.player.paused;i.player.pause();i.player.src=url;i.a.classList.toggle('selected',!output);i.ab.classList.toggle('selected',output);i.player.addEventListener('loadedmetadata',()=>{i.player.currentTime=Math.min(t,Math.max(0,i.player.duration-.01));if(playing)i.player.play().catch(()=>{});},{once:true});};i.a.onclick=()=>switchTo(false);i.ab.onclick=()=>switchTo(true);i.save.onclick=()=>{if(i.blob&&i.outputKey===key())L.download(i.blob,i.outputName);};items.push(i);setStatus(i,'queued / original untouched');added++;}if(added)msg('');update();}
function encode(pcm,s,ticket,i){return new Promise((resolve,reject)=>{rejectWorker=reject;worker=new Worker('/audio/encode-worker.js');worker.onerror=()=>{worker?.terminate();worker=null;reject(Error('Encoder could not start. Try a current browser.'));};worker.onmessage=({data:d})=>{if(ticket!==generation)return;if(d.error){worker.terminate();worker=null;rejectWorker=null;reject(Error(d.error));}else if(d.done){worker.terminate();worker=null;rejectWorker=null;resolve(d.blob);}else{i.progress.value=d.progress;setStatus(i,`encoding ${s.codec.toUpperCase()} / ${Math.round(d.progress)}%`);}};const buffers=pcm.map(a=>a.buffer);worker.postMessage({channels:buffers,rate:s.rate,bitrate:s.bitrate,codec:s.codec},buffers);});}
async function compress(){if(busy)return;const ticket=++generation,s=settings(),settingsKey=key();busyState(true);msg('');for(const i of items){if(ticket!==generation)break;if(i.blob&&i.outputKey===settingsKey)continue;dispose(i);i.progress.hidden=false;i.progress.value=0;setStatus(i,'decoding / checking audio');try{let b=await decode(i.file,s.rate);if(ticket!==generation)break;metadata(i,b);if(b.duration>600)throw Error('Over 10 minutes. Split this file first.');if(b.numberOfChannels>2)throw Error('Multichannel audio: use a dedicated editor to downmix first.');if(b.sampleRate!==s.rate)throw Error('Browser sample-rate conversion failed.');if(b.length*b.numberOfChannels>60000000)throw Error('Decoded audio is too large for this tab.');let pcm;if(s.mono&&b.numberOfChannels===2){const left=b.getChannelData(0),right=b.getChannelData(1),mono=new Float32Array(b.length);for(let n=0;n<mono.length;n++)mono[n]=(left[n]+right[n])*.5;pcm=[mono];}else pcm=Array.from({length:b.numberOfChannels},(_,c)=>new Float32Array(b.getChannelData(c)));b=null;setStatus(i,'encoding / high quality');const start=performance.now(),blob=await encode(pcm,s,ticket,i);if(ticket!==generation)break;if(!blob.size)throw Error('Encoder returned no audio.');i.blob=blob;i.url=URL.createObjectURL(blob);i.outputKey=settingsKey;i.outputName=i.file.name.replace(/\.[^.]+$/,'')+`-compressed-${s.bitrate}k.${s.codec==='opus'?'opus':'mp3'}`;i.save.disabled=i.ab.disabled=false;const saved=100*(1-blob.size/i.file.size);i.sizes.textContent='';const sizes=document.createElement('span');sizes.textContent=L.fmtBytes(i.file.size)+' → '+L.fmtBytes(blob.size);const change=document.createElement('span');change.className=saved>0?'saved':'grew';change.textContent=saved>0?saved.toFixed(1)+'% smaller':Math.abs(saved).toFixed(1)+'% larger / keep original for size';i.sizes.append(sizes,change);setStatus(i,`ready / ${s.codec.toUpperCase()} ${s.bitrate} kbps · ${s.mono?'mono':'channels kept'} · ${((performance.now()-start)/1000).toFixed(1)}s`);
}catch(e){if(ticket!==generation)break;const text=e.name==='EncodingError'||e.name==='NotSupportedError'?'This browser could not decode the file. Try WAV or MP3.':e.message;setStatus(i,text||'Could not process this file.',true);}finally{i.progress.hidden=true;}update();}if(ticket===generation){busyState(false);msg('batch finished / compare the audio before keeping it.');}}
async function zip(){const done=items.filter(i=>i.blob&&i.outputKey===key());if(!done.length)return;$('zip').disabled=true;try{const z=new JSZip();done.forEach((i,n)=>z.file(String(n+1).padStart(2,'0')+'-'+i.outputName,i.blob));L.download(await z.generateAsync({type:'blob',compression:'STORE'}),'lumen-audio.zip');}catch(e){msg('ZIP failed. Save files individually.',true);}finally{update();}}
L.dropzone($('dropzone'),$('fileInput'),add);for(const n of ['codec','quality','channels','rate'])$(n).addEventListener(n==='quality'?'input':'change',changed);$('compress').onclick=compress;$('cancel').onclick=cancel;$('zip').onclick=zip;$('clear').onclick=()=>{generation++;items.forEach(i=>{dispose(i);URL.revokeObjectURL(i.original);i.player.removeAttribute('src');i.player.load();});items=[];$('list').textContent='';msg('');update();};update();
})();
