import {createEncoder,Application,Signal} from 'libopus-wasm';
/* One packet per Ogg page: simple, valid lacing with explicit terminal zero for
   packets whose length is a multiple of 255. CRC follows the Ogg polynomial. */
function page(packet,serial,seq,granule,flags){const segments=Math.floor(packet.length/255)+1,header=new Uint8Array(27+segments+packet.length),v=new DataView(header.buffer);header.set([79,103,103,83,0,flags]);v.setBigUint64(6,BigInt(granule),true);v.setUint32(14,serial,true);v.setUint32(18,seq,true);header[26]=segments;for(let i=0;i<segments;i++)header[27+i]=Math.min(255,packet.length-i*255);header.set(packet,27+segments);let crc=0;for(const byte of header){crc^=byte<<24;for(let b=0;b<8;b++)crc=(crc&0x80000000)?(crc<<1)^0x04c11db7:crc<<1;}v.setUint32(22,crc>>>0,true);return header;}
self.onmessage=async({data:{channels,rate,bitrate,codec,depth}})=>{let enc;try{const pcm=channels.map(b=>new Float32Array(b)),n=pcm[0].length,ch=pcm.length,parts=[];
if(codec==='wav'){const bytes=depth/8,dataSize=n*ch*bytes,buffer=new ArrayBuffer(44+dataSize),v=new DataView(buffer),text=(offset,t)=>{for(let i=0;i<t.length;i++)v.setUint8(offset+i,t.charCodeAt(i));};text(0,'RIFF');v.setUint32(4,36+dataSize,true);text(8,'WAVE');text(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,rate,true);v.setUint32(28,rate*ch*bytes,true);v.setUint16(32,ch*bytes,true);v.setUint16(34,depth,true);text(36,'data');v.setUint32(40,dataSize,true);for(let i=0;i<n;i++){for(let c=0;c<ch;c++){const x=Math.max(-1,Math.min(1,pcm[c][i])),pos=44+(i*ch+c)*bytes;if(depth===16)v.setInt16(pos,Math.round(x*(x<0?32768:32767)),true);else{const num=Math.round(x*(x<0?8388608:8388607));v.setUint8(pos,num&255);v.setUint8(pos+1,(num>>8)&255);v.setUint8(pos+2,(num>>16)&255);}}if(i%48000===0)self.postMessage({progress:i/n*100});}parts.push(buffer);
}else if(codec==='opus'){
 enc=await createEncoder({channels:ch,sampleRate:48000,bitrate:bitrate*1000,complexity:10,vbr:true,application:Application.Audio,signal:Signal.Auto});const skip=enc.getLookahead(),serial=(Math.random()*0xffffffff)>>>0;
 const head=new Uint8Array(19);head.set(new TextEncoder().encode('OpusHead'));head[8]=1;head[9]=ch;const hv=new DataView(head.buffer);hv.setUint16(10,skip,true);hv.setUint32(12,rate,true);head[18]=0;parts.push(page(head,serial,0,0,2));const vendor=new TextEncoder().encode('lumen / libopus');const tags=new Uint8Array(16+vendor.length);tags.set(new TextEncoder().encode('OpusTags'));new DataView(tags.buffer).setUint32(8,vendor.length,true);tags.set(vendor,12);parts.push(page(tags,serial,1,0,0));const frames=Math.ceil((n+skip)/960);for(let frame=0;frame<frames;frame++){const input=new Float32Array(960*ch);for(let i=0;i<960;i++)for(let c=0;c<ch;c++)input[i*ch+c]=pcm[c][frame*960+i]||0;const packet=enc.encodeFloat(input);const last=frame===frames-1;parts.push(page(packet,serial,frame+2,last?n+skip:(frame+1)*960,last?4:0));if(frame%20===0)self.postMessage({progress:frame/frames*100});}
}else{
 importScripts(new URL('../vendor/lamejs/lame.min.js',self.location.href).href);enc=new lamejs.Mp3Encoder(ch,rate,bitrate);for(let offset=0;offset<n;offset+=1152){const block=pcm.map(a=>{const v=new Int16Array(Math.min(1152,n-offset));for(let i=0;i<v.length;i++){const s=Math.max(-1,Math.min(1,a[offset+i]));v[i]=s<0?s*32768:s*32767;}return v;});const packet=enc.encodeBuffer(block[0],block[1]);if(packet.length)parts.push(new Uint8Array(packet));if(offset%(1152*20)===0)self.postMessage({progress:offset/n*100});}const end=enc.flush();if(end.length)parts.push(new Uint8Array(end));
}
 const blob=new Blob(parts,{type:codec==='wav'?'audio/wav':codec==='opus'?'audio/ogg; codecs=opus':'audio/mpeg'});self.postMessage({done:true,blob});
}catch(e){self.postMessage({error:e.message||'Encoding failed'});}finally{enc?.free?.();}};
