/* Image-space crop geometry: preview scale never changes the stored rectangle. */
window.CropEditor = (() => {
 const $=id=>document.getElementById(id),dialog=$('cropDialog'),stage=$('cropStage'),box=$('cropBox');
 let bitmap=null,rect=null,ratio=0,apply=null,drag=null,previousFocus=null;
 const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
 function draw(){if(!rect||!bitmap)return;const {x,y,w,h}=rect;box.style.left=x/bitmap.width*100+'%';box.style.top=y/bitmap.height*100+'%';box.style.width=w/bitmap.width*100+'%';box.style.height=h/bitmap.height*100+'%';stage.classList.toggle('locked',!!ratio);for(const [id,v] of [['cropX',x],['cropY',y],['cropW',w],['cropH',h]])$(id).value=Math.round(v);$('cropInfo').textContent=`${Math.round(w)} × ${Math.round(h)} px crop · ${Math.round(w*h/(bitmap.width*bitmap.height)*100)}% of image`;}
 function fit(){if(!bitmap||!dialog.open)return;const maxW=dialog.clientWidth-64,maxH=Math.max(110,Math.min(480,window.innerHeight*.43)),scale=Math.min(maxW/bitmap.width,maxH/bitmap.height,1);stage.style.width=bitmap.width*scale+'px';stage.style.height=bitmap.height*scale+'px';const c=$('cropCanvas');c.width=Math.max(1,Math.round(bitmap.width*scale*devicePixelRatio));c.height=Math.max(1,Math.round(bitmap.height*scale*devicePixelRatio));c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);draw();}
 function move(r,dx,dy){return {...r,x:clamp(r.x+dx,0,bitmap.width-r.w),y:clamp(r.y+dy,0,bitmap.height-r.h)};}
 function resize(r,handle,dx,dy){const W=bitmap.width,H=bitmap.height,min=Math.min(8,W,H);if(ratio){const left=handle.includes('w'),top=handle.includes('n'),anchorX=left?r.x+r.w:r.x,anchorY=top?r.y+r.h:r.y;let w=r.w+(left?-dx:dx),h=r.h+(top?-dy:dy);if(Math.abs(dx)>=Math.abs(dy)*ratio)h=w/ratio;else w=h*ratio;const maxW=left?anchorX:W-anchorX,maxH=top?anchorY:H-anchorY;w=clamp(w,Math.min(min,maxW,maxH*ratio),Math.min(maxW,maxH*ratio));h=w/ratio;return {x:left?anchorX-w:anchorX,y:top?anchorY-h:anchorY,w,h};}
 let x=r.x,y=r.y,right=r.x+r.w,bottom=r.y+r.h;if(handle.includes('w'))x=clamp(x+dx,0,right-min);if(handle.includes('e'))right=clamp(right+dx,x+min,W);if(handle.includes('n'))y=clamp(y+dy,0,bottom-min);if(handle.includes('s'))bottom=clamp(bottom+dy,y+min,H);return {x,y,w:right-x,h:bottom-y};}
 function constrained(r){let w=clamp(r.w,1,bitmap.width),h=clamp(r.h,1,bitmap.height);if(ratio){w=Math.min(w,h*ratio,bitmap.width,bitmap.height*ratio);h=w/ratio;}return {x:clamp(r.x,0,bitmap.width-w),y:clamp(r.y,0,bitmap.height-h),w,h};}
 function chooseRatio(){const value=$('cropRatio').value;ratio=value==='free'?0:value==='original'?bitmap.width/bitmap.height:+value;if(ratio){const cx=rect.x+rect.w/2,cy=rect.y+rect.h/2;let w=Math.min(rect.w,rect.h*ratio),h=w/ratio;rect=constrained({x:cx-w/2,y:cy-h/2,w,h});}draw();}
 function open(bmp,current,name,onApply){bitmap=bmp;rect=current?{...current}:{x:0,y:0,w:bmp.width,h:bmp.height};ratio=0;apply=onApply;$('cropName').textContent=name;$('cropRatio').value='free';previousFocus=document.activeElement;dialog.showModal();document.body.classList.add('crop-open');fit();box.focus();}
 function close(){drag=null;dialog.close();}
 dialog.addEventListener('close',()=>{document.body.classList.remove('crop-open');bitmap=null;drag=null;previousFocus?.focus();});
 box.addEventListener('pointerdown',e=>{if(!bitmap||e.button>0||drag)return;e.preventDefault();drag={id:e.pointerId,x:e.clientX,y:e.clientY,rect:{...rect},handle:e.target.closest('[data-handle]')?.dataset.handle||null};box.setPointerCapture(e.pointerId);});
 box.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const bounds=stage.getBoundingClientRect(),dx=(e.clientX-drag.x)*bitmap.width/bounds.width,dy=(e.clientY-drag.y)*bitmap.height/bounds.height;rect=drag.handle?resize(drag.rect,drag.handle,dx,dy):move(drag.rect,dx,dy);draw();});
 const end=e=>{if(drag&&e.pointerId===drag.id){drag=null;if(box.hasPointerCapture(e.pointerId))box.releasePointerCapture(e.pointerId);}};box.addEventListener('pointerup',end);box.addEventListener('pointercancel',end);box.addEventListener('lostpointercapture',()=>drag=null);
 box.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||!bitmap)return;e.preventDefault();const d=e.shiftKey?10:1,dx=e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0,dy=e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0,handle=e.target.dataset.handle;rect=handle?resize(rect,handle,dx,dy):move(rect,dx,dy);draw();});
 for(const [id,key] of [['cropX','x'],['cropY','y'],['cropW','w'],['cropH','h']])$(id).addEventListener('change',()=>{let value=+$(id).value;if(!Number.isFinite(value))return;const r={...rect,[key]:value};if(ratio&&key==='w')r.h=r.w/ratio;if(ratio&&key==='h')r.w=r.h*ratio;rect=constrained(r);draw();});
 $('cropRatio').addEventListener('change',chooseRatio);$('cropReset').onclick=()=>{rect={x:0,y:0,w:bitmap.width,h:bitmap.height};chooseRatio();};$('cropCancel').onclick=$('cropClose').onclick=close;$('cropApply').onclick=()=>{const x=Math.round(rect.x),y=Math.round(rect.y),right=Math.min(bitmap.width,Math.round(rect.x+rect.w)),bottom=Math.min(bitmap.height,Math.round(rect.y+rect.h)),result={x,y,w:Math.max(1,right-x),h:Math.max(1,bottom-y)};const callback=apply;close();callback(result);};window.addEventListener('resize',fit);
 return {open,close};
})();
