(() => {
 const $=id=>document.getElementById(id), names=['detail','noise','light','colour'], presets={natural:[35,15,30,15],crisp:[65,10,20,10],lowlight:[25,55,65,12]};
 let bitmap=null,file=null,sourceURL=null,resultURL=null,resultCanvas=null,worker=null,busy=false,job=0,loading=0,resizeReject=null,workerReject=null;
 const resizer=pica({features:['js','wasm','ww'],concurrency:2,tile:512});
 const message=(text,error=false)=>{$('message').textContent=text;$('message').className='msg'+(error?' err':'');};
 function releaseResult(){if(resultURL)URL.revokeObjectURL(resultURL);resultURL=null;resultCanvas=null;$('after').hidden=$('divider').hidden=$('afterBadge').hidden=true;$('download').disabled=$('split').disabled=true;$('resultInfo').textContent='';}
 function limits(){if(!bitmap)return;const ai=$('engine').value==='ai';if(ai)$('scale').value='2';$('scale').disabled=ai||busy;const scale=+$('scale').value,w=bitmap.width*scale,h=bitmap.height*scale;const valid=w*h<=24000000&&Math.max(w,h)<=10000;const aiValid=bitmap.width*bitmap.height<=1000000&&Math.max(bitmap.width,bitmap.height)<=1024;
  $('engineNote').textContent=ai?'local ESRGAN-slim model. slower, may infer detail. opaque images only.':'edge-aware noise cleanup + high-quality resampling. no invented detail.';
  $('target').textContent=`${w.toLocaleString()} × ${h.toLocaleString()} px`+(!valid?' / over the 24 MP or 10,000 px limit':'')+(ai&&!aiValid?' / AI needs a smaller image':'');$('apply').disabled=busy||!valid||(ai&&!aiValid);
 }
 function split(){const p=$('split').value;$('after').style.clipPath=`inset(0 0 0 ${p}%)`;$('divider').style.left=p+'%';}
 function fit(){if(!bitmap)return;const zoom=$('zoom').getAttribute('aria-pressed')==='true',scale=resultCanvas?resultCanvas.width/bitmap.width:1;const w=bitmap.width*scale,h=bitmap.height*scale;const ratio=zoom?1:Math.min($('viewport').clientWidth/w,520/h);$('compare').style.width=Math.round(w*ratio)+'px';$('compare').style.height=Math.round(h*ratio)+'px';$('viewport').classList.toggle('zoomed',zoom);}
 function setBusy(value){busy=value;names.forEach(n=>$(n).disabled=value);$('engine').disabled=value;$('cancel').hidden=!value;$('progress').hidden=!value;$('download').disabled=value||!resultCanvas;document.querySelectorAll('[data-preset]').forEach(b=>b.disabled=value);limits();}
 function cancel(){job++;worker?.terminate();worker=null;workerReject?.(Error('Cancelled'));workerReject=null;resizeReject?.(Error('Cancelled'));resizeReject=null;setBusy(false);$('status').textContent='cancelled / your original is unchanged';}
 function changed(){releaseResult();$('status').textContent='settings changed / enhance to apply';limits();fit();}
 async function load(files){if(!files.length)return;if(files.length>1)message('one image at a time. using the first image.');else message('');const f=files[0],ticket=++loading;
  if(!['image/jpeg','image/png','image/webp'].includes(f.type)){message('choose a JPG, PNG or WebP image.',true);return;}if(!f.size||f.size>40*1024*1024){message('choose a non-empty image under 40 MB.',true);return;}
  cancel();$('status').textContent='reading image';try{const b=await createImageBitmap(f);if(ticket!==loading){b.close();return;}if(b.width*b.height>16000000||Math.max(b.width,b.height)>10000){b.close();throw Error('This image is too large. Resize below 16 megapixels and 10,000 px per side first.');}
   bitmap?.close();bitmap=b;file=f;releaseResult();if(sourceURL)URL.revokeObjectURL(sourceURL);sourceURL=URL.createObjectURL(f);$('before').src=sourceURL;$('workspace').hidden=false;$('dropzone').hidden=true;$('filename').textContent=f.name;$('dimensions').textContent=`${b.width} × ${b.height} px · ${L.fmtBytes(f.size)}`;$('zoom').setAttribute('aria-pressed','false');$('zoom').textContent='view at 100%';$('status').textContent='ready when you are';$('engine').value='fast';$('scale').value='1';limits();requestAnimationFrame(fit);
  }catch(e){message(e.message==='The source image could not be decoded.'?'could not read this image. try another file.':e.message,true);}
 }
 function runWorker(path,image,settings,ticket,offset,range){return new Promise((resolve,reject)=>{workerReject=reject;worker=new Worker(path);worker.onerror=()=>{worker?.terminate();worker=null;reject(Error('Processing unavailable on this browser. Try a current Safari or Chrome.'));};worker.onmessage=({data})=>{if(ticket!==job)return;if(data.error){worker.terminate();worker=null;reject(Error(data.error));}else if(data.done){worker.terminate();worker=null;workerReject=null;resolve(new ImageData(new Uint8ClampedArray(data.buffer),data.width,data.height));}else{$('progress').value=offset+data.progress*range;$('status').textContent=data.label;}};worker.postMessage({buffer:image.data.buffer,width:image.width,height:image.height,settings},[image.data.buffer]);});}
 async function enhance(){if(!bitmap||busy)return;const ticket=++job,start=performance.now(),s=Object.fromEntries(names.map(n=>[n,+$(n).value])),ai=$('engine').value==='ai',scale=+$('scale').value;
  releaseResult();setBusy(true);message('');$('progress').value=0;$('status').textContent='preparing pixels';
  try{const source=document.createElement('canvas');source.width=bitmap.width;source.height=bitmap.height;const ctx=source.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0);let image=ctx.getImageData(0,0,source.width,source.height);
   if(ai){for(let i=3;i<image.data.length;i+=4)if(image.data[i]!==255)throw Error('AI does not keep transparency. Use precise / fast for this image.');}
   image=await runWorker(L.url('/enhance/finish-worker.js'),image,s,ticket,0,ai?.16:.65);if(ticket!==job)return;source.getContext('2d').putImageData(image,0,0);
   let output;
   if(ai){image=await runWorker(L.url('/enhance/ai-worker.js'),image,null,ticket,18,.75);if(ticket!==job)return;output=document.createElement('canvas');output.width=image.width;output.height=image.height;output.getContext('2d').putImageData(image,0,0);}
   else if(scale===1){output=source;}
   else {output=document.createElement('canvas');output.width=source.width*scale;output.height=source.height*scale;$('status').textContent='resampling at full resolution';$('progress').value=70;const cancelToken=new Promise((_,reject)=>{resizeReject=reject;});await resizer.resize(source,output,{filter:'mks2013',cancelToken});resizeReject=null;}
   if(ticket!==job)return;$('status').textContent='preparing comparison';const blob=await new Promise((resolve,reject)=>output.toBlob(b=>b?resolve(b):reject(Error('Could not encode this image. Try a smaller output.')),'image/png'));if(ticket!==job)return;
   resultCanvas=output;resultURL=URL.createObjectURL(blob);$('after').src=resultURL;await $('after').decode();if(ticket!==job)return;$('after').hidden=$('divider').hidden=$('afterBadge').hidden=false;$('split').disabled=false;$('split').value=50;split();fit();$('resultInfo').textContent=`${output.width} × ${output.height} px · PNG ${L.fmtBytes(blob.size)} · ${ai?'AI detail':'precise / fast'} · ${((performance.now()-start)/1000).toFixed(1)}s`;$('status').textContent='finished / drag the comparison slider';setBusy(false);
  }catch(e){if(ticket!==job)return;resizeReject=null;workerReject=null;releaseResult();setBusy(false);message(e.message||'Could not process this image. Try a smaller output.',true);$('status').textContent='not finished / your original is unchanged';}
 }
 async function download(){if(!resultCanvas||busy)return;const canvas=resultCanvas,f=file,mime=$('format').value;$('download').disabled=true;
  try{let c=canvas;if(mime==='image/jpeg'){c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(canvas,0,0);}const blob=await new Promise(resolve=>c.toBlob(resolve,mime,.95));if(!blob)throw Error('Could not export. Try PNG.');const ext=blob.type==='image/png'?'png':blob.type==='image/webp'?'webp':'jpg';L.download(blob,f.name.replace(/\.[^.]+$/,'')+'-enhanced.'+ext);if(blob.type!==mime)message('Your browser used '+ext.toUpperCase()+' instead of the requested format.');}
  catch(e){message(e.message,true);}finally{$('download').disabled=busy||!resultCanvas;}
 }
 L.dropzone($('dropzone'),$('fileInput'),load);
 names.forEach(n=>$(n).addEventListener('input',()=>{$(n+'Value').textContent=$(n).value;document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed','false'));changed();}));
 document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{presets[b.dataset.preset].forEach((v,i)=>{$(names[i]).value=v;$(names[i]+'Value').textContent=v;});document.querySelectorAll('[data-preset]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));changed();}));
 ['engine','scale'].forEach(n=>$(n).addEventListener('change',changed));$('split').addEventListener('input',split);$('apply').addEventListener('click',enhance);$('cancel').addEventListener('click',cancel);$('download').addEventListener('click',download);
 $('zoom').addEventListener('click',()=>{const on=$('zoom').getAttribute('aria-pressed')!=='true';$('zoom').setAttribute('aria-pressed',String(on));$('zoom').textContent=on?'fit image':'view at 100%';fit();});window.addEventListener('resize',fit);
 $('clear').addEventListener('click',()=>{loading++;cancel();releaseResult();bitmap?.close();bitmap=null;file=null;if(sourceURL)URL.revokeObjectURL(sourceURL);sourceURL=null;$('workspace').hidden=true;$('dropzone').hidden=false;$('before').removeAttribute('src');message('');$('dropzone').focus();});
})();
